# Generated by Django 4.1.5 on 2023-01-15 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List_Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50, unique=True)),
                ('item_cost', models.DecimalField(decimal_places=2, max_digits=15)),
                ('item_purchased', models.BooleanField(default=False)),
                ('item_deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
